title: "Riley Shen"
author: "Riley Shen"
description: "Creative Developer and Artist"
url: "https://rileys123.github.io" # Update with your actual URL
baseurl: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

theme: jekyll-theme-minimal
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap 


# Layout

show_social: true 
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

navigation:
  - name: "Home"
    url: "/"
  - name: "Projects" 
    url: "/projects/"
  - name: "Artwork"
    url: "/artwork/"

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:rileys435123@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/rileys123"}
  - {title: LinkedIn, icon: linkedin, url: "https://linkedin.com/rileys1"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/


