title: "Riley Shen"
author: "Riley Shen"
description: "Personal Projects"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true 
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "README.md", title: "About me"}
  - {file: "projects.md", title: "Projects"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:rileys435123@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/rileys123"}
  - {title: LinkedIn, icon: rss, url: "linkedin.com/rileys1"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
