name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master # Adjust if your source branch is different (e.g., main)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Or your specific Ruby version if different
          bundler-cache: true # Installs dependencies with Bundler

      - name: Clear Jekyll cache # THIS IS THE ADDED STEP TO FORCE FRESH BUILD
        run: rm -rf .jekyll-cache

      - name: Build with Jekyll
        run: bundle exec jekyll build --verbose # Add --verbose for more output in logs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master' # Ensure this matches your source branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # If you want to force push and overwrite history on gh-pages (use with caution)
          # force_orphan: true
